name: GitHub Activity Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: generate-github-cards
    steps:
      - uses: actions/checkout@v3
      - uses: ashutosh00710/github-readme-activity-graph@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/activity-graph.svg
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: activity-graph-output
